{{- if .Values.kerberoshub.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kerberoshub.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.kerberoshub.serviceAccount.annotations | nindent 4 }}
  {{- with .Values.kerberoshub.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}